services:
  backend:
    build:
      context: .
      dockerfile: infra/dockerfiles/backend/Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    entrypoint: /entrypoint.sh

  frontend:
    build:
      context: .
      dockerfile: infra/dockerfiles/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # volume anônimo para evitar sobrescrever
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --port 3000 --hostname 0.0.0.0

  database:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
